[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['Shougo/context_filetype.vim']

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo ='Shougo/neosnippet'

[[plugins]]
repo ='Shougo/neosnippet-snippets'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['/vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo ='tpope/vim-endwise'
on_i = 1
on_ft = ['ruby']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo ='ujihisa/neco-look'

[[plugins]]
repo ='osyo-manga/vim-marching'

[[plugins]]
#shift v で範囲選択 ctrl -(ハイフン）2回でコメントアウト
repo ='tomtom/tcomment_vim'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]#横にdirtree表示
repo ='scrooloose/nerdtree'
hook_add = 'let g:nerdtree_tabs_open_console_startup = 0'

#C/C++
[[plugins]]
repo = 'justinmk/vim-syntax-extra'

[[plugins]]
repo ='octol/vim-cpp-enhanced-highlight'
hook_add = 'let g:cpp_class_scope_highlight = 1'
hook_add = 'let g:cpp_member_variable_highlight = 1'
hook_add = 'let g:cpp_class_decl_heighligjt = 1'

[[plugins]]
repo = 'vim-jp/cpp-vim'

[[plugins]]
repo = 'w0rp/ale'
#hook_source = 'let g:ale_lint_on_text_changed = "never" '
#hook_source = 'let g:ale_lint_on_enter = 0'

#js系
[[plugins]] #js-plugin
repo ='pangloss/vim-javascript'

[[plugins]] #vue-js系
repo ='othree/yajs.vim'

[[plugins]] #js-syntax
repo ='jelera/vim-javascript-syntax'

[[plugins]] #wasureta
repo ='posva/vim-vue'

#git diff
[[plugins]] #git変更行教えてくれる
repo ='airblade/vim-gitgutter'

#toml
[[plugins]]
#toml-syntax
repo ='cespare/vim-toml'

#yaml
[[plugins]]
repo = 'chase/vim-ansible-yaml'

[[plugins]]
repos = 'maralla/vim-toml-enhance'
depends = ['cespare/vim-toml']

#markdown系
#markdown-syntax
[[plugins]]
repo ='plasticboy/vim-markdown'

#markdown-preview
[[plugins]]
repo ='kannokanno/previm'

#markdown-browser
[[plugins]]
repo ='tyru/open-browser.vim'
hook_add = 'let g:vim_markdown_math = 1'
hook_add = '''
au PrevimSettings BufNewFile,BufRead *.{md,mdwn,mkd,mkdn,mark*} set filetype=markdown
'''

#tex
[[plugins]]
repo ='lervag/vimtex'

#ruby
[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = ['ruby']

[[plugins]]
repo ='vim-ruby/vim-ruby'

[[plugins]]
repo ='bbatsov/rubocop'
