# ruby syntax
[[plugins]]
repo ='vim-ruby/vim-ruby'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'osyo-manga/vim-monster'
on_i = 1
hook_add = '''
let g:monster#completion#rcodetools#backend = "async_rct_complete"
let g:deoplete#sources#omni#input_patterns = {
  \ "ruby" : '[^. *\t]\.\w*\|\h\w*::',
  \}
'''

# ruby lint
[[plugins]]
repo ='bbatsov/rubocop'

[[plugins]]
repo ='tpope/vim-endwise'
on_i = 1
on_ft = ['ruby']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']
