[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'davidhalter/jedi-vim'
hook_add = '''
let g:jedi#auto_inirializeation   = 0 "自動初期化無効
let g:jedi#auto_vim_configuration = 0 " completeオプションの上書きしない
let g:jedi#popup_on_dot           = 0 " ドット入力は自動で補完しない
let g:jedi#popup_select_first     = 0 " 補完候補の１番目を選択しない
let g:jedi#show_call_sifnatures   = 0 " 関数の引数表示を無効
"autocmd FileType python setlocal omnifunc=jedi#completions 
'''

[[plugins]]
repo = 'vim-python/python-syntax'
hook_add = '''
let g:python_hilight_builtins = 1
let g:python_hilight_class_vars = 1
let g:python_hilight_exceptions = 1
let g:python_hilight_operators = 1
'''
